# Generated by Django 5.0.6 on 2024-06-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_rename_plans_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='time',
        ),
    ]
